SECRET_KEY = 'ViCAZJknGALnmoVcMSimhmT5GT4gIpcK89MCiJGtzxC'

[DATABASE]
PROVIDER = 'postgres'
HOST = '127.0.0.1'
PORT = 5432
NAME = 'pia'
USER = 'pia'
PASSWORD = 'pia'

[GAME]
BOARD_DEFAULT_SIZE = 15
BOARD_MAX_SIZE = 4096

[UID]
LENGTH = 64


